# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20171214_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
